
    export const STAFF_REQUEST = "STAFF_REQUEST";
    export const STAFF_REQUEST_SUCCESS = "STAFF_REQUEST_SUCCESS";
    export const STAFF_REQUEST_FAIL = "STAFF_REQUEST_FAIL";
   
    export const ADD_STAFF_TO_CART_REQUEST = "ADD_STAFF_TO_CART_REQUEST";
    export const ADD_STAFF_TO_CART_REQUEST_SUCCESS = "ADD_STAFF_TO_CART_REQUEST_SUCCESS";
    export const ADD_STAFF_TO_CART_REQUEST_FAIL = "ADD_STAFF_TO_CART_REQUEST_FAIL";


    export const ADD_NEW_STAFF_REQUEST = "ADD_NEW_STAFF_REQUEST";
    export const ADD_NEW_STAFF_REQUEST_SUCCESS = "ADD_NEW_STAFF_REQUEST_SUCCESS";
    export const ADD_NEW_STAFF_REQUEST_FAIL = "ADD_NEW_STAFF_REQUEST_FAIL";


    
//User
    //usersAuthAction
    export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
    export const USER_AUTH_REQUEST_SUCCESS = "USER_AUTH_REQUEST_SUCCESS";
    export const USER_AUTH_REQUEST_FAIL = "USER_AUTH_REQUEST_FAIL";
    
    //usersRegistrAction
    export const USER_REG_REQUEST = "USER_REG_REQUEST";
    export const USER_REG_REQUEST_SUCCESS = "USER_REG_REQUEST_SUCCESS";
    export const USER_REG_REQUEST_FAIL = "USER_REG_REQUEST_FAIL";

    //getUsersById
    export const GET_USER_REQUEST_BY_ID = "GET_USER_REQUEST_BY_ID";
    export const GET_USER_REQUEST_SUCCESS_BY_ID = "GET_USER_REQUEST_SUCCESS_BY_ID";
    export const GET_USER_REQUEST_FAIL_BY_ID = "GET_USER_REQUEST_FAIL_BY_ID";


    export const DELETE_STAFF = "DELETE_STAFF"

    export const REMOVE_USER = "REMOVE_USER"